-- INITIAL DATA FOR PRESTIGEUM ACADEMIA
-- Run this in your Supabase SQL Editor AFTER running pa_schema.sql

-- 1. INITIAL TRAININGS
INSERT INTO pa_trainings (id, title, category, level, format, date, time, duration, location, instructor, instructor_title, seats, seats_left, price, deadline, image_url, description, short_desc, language, max_participants, objectives, modules, target_audience)
VALUES
('qaqc-001', 'Project Quality Management Training', 'QA/QC', 'Intermediate', 'Offline', 'August 23, 2026', '08:00 - 17:00 WIB', '2 Days / 16 Hours', 'Jakarta Convention Center, Jakarta', 'Ir. Budi Santoso, M.Eng', 'Senior QA/QC Engineer — PT. Rekayasa Industri', 50, 18, '1500000', 'August 18, 2026', 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', 'A comprehensive 2-day intensive training covering the full lifecycle of project quality management in engineering environments.', 'Master quality assurance and control frameworks used in real engineering projects.', 'Indonesian', 50, '["Understand QA/QC roles", "Develop quality planning", "Apply quality assurance", "Conduct inspections"]', '[{"title": "Introduction", "desc": "Foundations", "duration": "2 Hours"}]', 'Junior to mid-level engineers'),
('civil-002', 'Structural Analysis for Civil Engineers', 'Civil Engineering', 'Advanced', 'Hybrid', 'September 5, 2026', '09:00 - 16:00 WIB', '3 Days / 18 Hours', 'Bandung Institute of Technology, Bandung', 'Dr. Hendra Wijaya, S.T., M.T.', 'Structural Engineering Specialist — PT. Waskita Karya', 40, 12, '2000000', 'August 30, 2026', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', 'Deep-dive into structural analysis methods including finite element analysis and design standards.', 'Advanced structural analysis techniques for modern civil engineering projects.', 'Indonesian', 40, '["Apply FEM", "Interpret loads", "Design RC/Steel"]', '[{"title": "Mechanics", "desc": "Principles", "duration": "3 Hours"}]', 'Mid to senior civil engineers'),
('elec-003', 'Industrial Electrical Systems & Safety', 'Electrical Engineering', 'Beginner', 'Online', 'August 30, 2026', '08:00 - 12:00 WIB', '1 Day / 4 Hours', 'Online — Zoom', 'Ir. Andi Kusuma, M.Sc.', 'Electrical Safety Engineer — PLN', 100, 63, 'Free', 'August 28, 2026', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', 'An introductory online session covering electrical system design and safety protocols.', 'Fundamentals of industrial electrical systems with a focus on safety protocols.', 'Indonesian', 100, '["Understand power systems", "Identify protection", "Apply safety"]', '[{"title": "Power Systems", "desc": "Overview", "duration": "1 Hour"}]', 'Students and fresh graduates');

-- 2. INITIAL ARTICLES
INSERT INTO pa_articles (title, category, excerpt, author, body, image_url, read_time)
VALUES
('Why QA/QC is Non-Negotiable in Engineering Projects', 'QA/QC', 'Quality failures in engineering projects can cost millions and endanger lives.', 'Ir. Budi Santoso', 'Quality assurance and quality control are often treated as afterthoughts...', 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', '6 min read'),
('The Engineer''s Guide to Career Transition into Project Management', 'Career', 'Many engineers hit a ceiling in technical roles.', 'Reza Firmansyah, PMP', 'The transition from technical engineer to project manager is one of the most rewarding...', 'https://images.unsplash.com/photo-1619759247378-6a73e3ad45f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', '8 min read');

-- 3. INITIAL GALLERY
INSERT INTO pa_gallery (category, title, caption, image_url, date)
VALUES
('Training', 'QA/QC Intensive Workshop', 'Participants hands-on quality inspection training', 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', 'July 2026'),
('Workshop', 'Structural Analysis Workshop', 'Advanced structural analysis session with Dr. Hendra', 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixlib=rb-4.1.0&q=80&w=800', 'June 2026');
